[project]
name = "seldon"
version = "0.1.0"
description = "A code for opinion dynamics simulations."
authors = ["Moritz Sallermann <m.sallermann@fz-juelich.de>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64"]

[tasks]

[dependencies]
fmt = "10.1.1.*"
meson = "1.2.1.*"
compilers = "1.6.0.*"
pkg-config = "0.29.2.*"
cmake = "3.27.5.*"
ninja = "1.11.1.*"
tomlplusplus = "3.3.0.*"
cpp-argparse = "2.9.*"
clang-format = "16.0.6.*"
catch2 = "3.4.0.*"
